name: Build and Push Docker Image

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build Docker image
              run: docker build -t fbapi .

            - name: Tag Docker image
              run: docker tag rudolf jotrorox/fbapi:latest

            - name: Push Docker image
              run: docker push jotrorox/fbapi:latest