name: Node.js Test

on:
  push:
    branches: 
        - master
  pull_request:
    branches: 
        - master

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: node:alpine

    steps:
    - uses: actions/checkout@v4
    - run: npm install
    - run: npm ci